mainSections = ["docs"]
rssFullContent = true

[footer]
since = 2026

[sidebar]
emoji = "ğŸ“"
subtitle = "Architectural pattern enforcement and discovery tool"

[article]
[article.license]
enabled = false

[widgets]
homepage = [
    { type = "search" },
    { type = "archives", params = { limit = 5 } },
    { type = "tag-cloud", params = { limit = 10 } },
]
page = [{ type = "toc" }]

[comments]
enabled = false
