baseURL = "https://coreyt.github.io/sine/"
languageCode = "en-us"
title = "Sine - Architectural Pattern Enforcement"
theme = "learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  description = "Architectural pattern enforcement and discovery tool"
  author = "Corey Taylor"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "blue"

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub"
url = "https://github.com/coreyt/sine"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-download'></i> Install"
url = "https://github.com/coreyt/sine#installation"
weight = 20
